let x = 10 < 9;
console.log(x);
x = true;
console.log(x);
console.log(Boolean(x));
let y;
console.log(y);
console.log(Boolean(y));
let z = null;
console.log(Boolean(z));
z = NaN;
console.log(Boolean(z));